// Angular/DevRant/src/app/rant-details/rant-details.component.ts
import { Component, OnInit } from '@angular/core';
import { DevRantApiService } from '../Service/devrant_api';

@Component({
  selector: 'app-rant-details',
  templateUrl: './rant-details.component.html',
  styleUrls: ['./rant-details.component.css']
})
export class RantDetailsComponent implements OnInit {

  constructor(private devrantApi:DevRantApiService,) { }

  ngOnInit() {
  
  }

}

<section class="main layout--center">
    <div class="main__content layout--wrapped">
<div class="rant-details layout--center">
  <section class="post-hero">
    <div class="post-hero__inner">
      <div class="score">
        <div class="score__up layout--center">++</div>
        <div class="score__board layout--center">100</div>
        <div class="score__down layout--center">--</div>
      </div>
      <div class="post-hero__body">
        <div class="profile">
          <div class="profile__picture">
            <svg height="36" width="36">
              <circle cx="18" cy="18" r="18" fill="#5c5f6f" />
            </svg>
          </div>
          <div class="profile__name">
            Elon
          </div>
        </div>
        <div class="post__details">
          Lorem ipsum
        </div>
      </div>
    </div>
    <div class="post-hero__footer">
      <div class="post-hero__delete">DELETE</div>
      <div class="post-hero__time">2m ago</div>
    </div>
  </section>

  <section class="comments layout--center">
    <h1 class="comments__title"><span>#</span>Comments</h1>

    <section class="comment">
      <div class="comment__inner">
        <div class="comment__body">
          <div class="profile">
            <div class="profile__picture">
              <svg height="36" width="36">
                <circle cx="18" cy="18" r="18" fill="#5c5f6f" />
              </svg>
            </div>
            <div class="profile__name">
              Elon
            </div>
          </div>
          <div class="post__details">
            Lorem ipsum
            <br />
          </div>
        </div>
      </div>
      <div class="comment__footer">
        <div class="comment__delete">DELETE</div>
        <div class="comment__time">2m ago</div>
      </div>
    </section>
  </section>

  <div class="rant__comment layout--center" title="Comment">
    <svg class="icon" viewBox="0 0 31 32" width="100%" height="100%">
      <path
        d="M24.732 24.371v7.629l-7.267-7.267h-8.808c-4.781 
                  0-8.657-3.875-8.657-8.657v-7.42c0-4.781 3.876-8.657 
                  8.657-8.657h13.604c4.781 0 8.657 3.875 8.657 8.657v7.42c0 
                  3.922-2.61 7.23-6.186 8.294z"
      ></path>
    </svg>
  </div>
</div>
</div>
</section>

// React/devrant/src/components/RantDetails.js
/**
 * Author : Nadun Chamikara
 * Date : 2019/02/23
 */

import React, {Component} from 'react';

class RantDetails extends Component {

    render() {
        let rantId = this.props.match.params.rantid;
        
        return (
            <div className="rant-details layout--center">

                <section className="post-hero">
                    <div className="post-hero__inner">
                        <div className="score">
                            <div className="score__up layout--center">++</div>
                            <div className="score__board layout--center">100</div>
                            <div className="score__down layout--center">--</div>
                        </div>
                        <div className="post-hero__body">
                            <div className="profile">
                                <div className="profile__picture">
                                    <svg height="36" width="36">
                                        <circle cx="18" cy="18" r="18" fill="#5c5f6f"/>
                                    </svg>
                                </div>
                                <div className="profile__name">
                                    Elon
                                </div>
                            </div>
                            <div className="post__details">
                                Lorem ipsum
                            </div>
                        </div>
                    </div>
                    <div className="post-hero__footer">
                        <div className="post-hero__delete">DELETE</div>
                        <div className="post-hero__time">2m ago</div>
                    </div>
                </section>

                <section className="comments layout--center">

                    <h1 className="comments__title"><span>#</span>Comments</h1>

                    <section className="comment">
                        <div className="comment__inner">
                            <div className="comment__body">
                                <div className="profile">
                                    <div className="profile__picture">
                                        <svg height="36" width="36">
                                            <circle cx="18" cy="18" r="18" fill="#5c5f6f"/>
                                        </svg>
                                    </div>
                                    <div className="profile__name">
                                        Elon
                                    </div>
                                </div>
                                <div className="post__details">
                                    Lorem ipsum
                                    <br/>
                                </div>
                            </div>
                        </div>
                        <div className="comment__footer">
                            <div className="comment__delete">DELETE</div>
                            <div className="comment__time">2m ago</div>
                        </div>
                    </section>

                </section>

                <div className="rant__comment layout--center" title="Comment">
                    <svg className="icon" viewBox="0 0 31 32" width="100%" height="100%">
                        <path d="M24.732 24.371v7.629l-7.267-7.267h-8.808c-4.781
        0-8.657-3.875-8.657-8.657v-7.42c0-4.781 3.876-8.657 
        8.657-8.657h13.604c4.781 0 8.657 3.875 8.657 8.657v7.42c0 
        3.922-2.61 7.23-6.186 8.294z"></path>
                    </svg>
                </div>

            </div>

        )
    }
}

export default RantDetails;
