// React/devrant/src/components/Alert.js
/**
 * Author : Nadun Chamikara
 * Date : 2019/02/23
 */

import React, {Component} from 'react';

class Alert extends Component {
    constructor(props) {
        super(props)
        this.state = {}
    }


    render() {
        return (
            <div className="popup popup--open">
               <div className="popup__header">
                   <div title="Close" className="close layout--center">
                       X
                   </div>
               </div>
               <div className="popup__body layout--center">
                   <div className="popup__body-inner">

                       <div className="form">
                           <div className="form__title">
                               <span className="highlight">#</span>OOPS!
                           </div>
                           <div className="form__description">
                               You can not vote on your own post :)
                           </div>
                           <form name="alert">
                               <div className="alert">
                                   <input type="submit" value="OK" />
                               </div>
                           </form>
                       </div>

                   </div>
               </div>
           </div>
        )
    }
}

export default Alert;

// Angular/DevRant/src/app/alert/alert.component.ts
import { Component, OnInit, Input } from '@angular/core';

@Component({
  selector: 'app-alert',
  templateUrl: './alert.component.html',
  styleUrls: ['./alert.component.css']
})
export class AlertComponent implements OnInit {

  @Input() title;
  @Input() description;

  alertTitle:any="";
  alertDescription:any="";

  constructor() {
    this.alertTitle=this.title;
    this.alertDescription=this.description;
   }

  ngOnInit() {
  }

}

<!-- Start of alert popup -->
<!-- ======================= -->

<div class="popup popup--open">
  <div class="popup__header">
      <div title="Close" class="close layout--center">
          X
      </div>
  </div>
  <div class="popup__body layout--center">
      <div class="popup__body-inner">

          <div class="form">
              <div class="form__title">
                  <span class="highlight">#</span>{{alertTitle}}!
              </div>
              <div class="form__description">
                  <!-- You can not vote on your own post :) -->
                  {{alertDescription}}
              </div>
              <form name="alert">
                  <div class="alert">
                      <input type="submit" value="OK" />
                  </div>
              </form>
          </div>

      </div>
  </div>
</div>

<!-- ======================= -->
<!-- End of alert popup -->
