// React/devrant/src/components/Header.js
import React, {Component} from 'react';

class Header extends Component{

    render(){
        return (
            <section className="header layout--center">
                <div className="header__content layout--wrapped">
                    <div className="brand">
                        <a href="/">
                            <div className="brand__name"><span>#</span>DEVRANT</div>
                        </a>
                    </div>

                    User Profile
                    <div className="profile layout--center">
                        <div className="profile__picture">
                            <svg height="36" width="36">
                                <circle cx="18" cy="18" r="18" fill="#5c5f6f"></circle>
                            </svg>
                        </div>
                        <div className="profile__name">Elon</div>
                    </div>

                    <div className="join">
                        {/* <span>Join</span> */}
                        <span>Sign Out</span>
                    </div>
                </div>
            </section>
        )
    }
}

export default Header;

// Angular/DevRant/src/app/header/header.component.ts
import { Component, OnInit } from '@angular/core';
import { LoginService } from '../login-popup/login-popup.service';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.css']
})
export class HeaderComponent implements OnInit {

  constructor(private loginServic: LoginService) { }

  ngOnInit() {
  }

  openLoginPopup(){
    this.loginServic.display(true);
  }

}

<section class="header layout--center">
  <div class="header__content layout--wrapped">
      <div class="brand">
          <a href="/"><div class="brand__name"><span>#</span>DEVRANT</div></a>
      </div>

      <!-- User Profile -->
      <div class="profile layout--center" *ngIf="login">
          <div class="profile__picture">
              <svg height="36" width="36">
                  <circle cx="18" cy="18" r="18" fill="#5c5f6f"></circle>
              </svg>
          </div>
          <div class="profile__name">{{username}}</div>
      </div>

      <div class="join">
          <span (click)="openLoginPopup()" *ngIf="logout">Join</span>
          <span *ngIf="login" (click)="clickLogout()">Sign Out</span>
      </div>
  </div>
</section>
