// React/devrant/src/components/Comment.js
/**
 * Author : Nadun Chamikara
 * Date : 2019/02/23
 */

import React, {Component} from 'react';

class Comment extends Component {

    constructor(props){
        super(props)
        this.state = {
            comment : {
                "comment": "",
                "id": "",
                "timestamp": 0,
                "author": "",
                "isMyComment": false,
                "displayTime": ""
            },
            rantId : ''
        }

    }

    componentWillReceiveProps(nextProps, nextContext) {
        this.setState({
            comment : nextProps.comment,
            rantId : nextProps.rantId
        })
    }

    render() {
        let comment = this.state.comment

        return (
            <section className="comment">
                <div className="comment__inner">
                    <div className="comment__body">
                        <div className="profile">
                            <div className="profile__picture">
                                <svg height="36" width="36">
                                    <circle cx="18" cy="18" r="18" fill="#5c5f6f"/>
                                </svg>
                            </div>
                            <div className="profile__name">
                                {comment.author}
                            </div>
                        </div>
                        <div className="post__details">
                            {comment.comment}
                            <br/>
                        </div>
                    </div>
                </div>
                <div className="comment__footer">
                    {comment.isMyComment && <div className="comment__delete">DELETE</div>}
                    <div className="comment__time">{comment.displayTime}</div>
                </div>
            </section>
        )
    }
}

export default Comment;

// Angular/DevRant/src/app/comment/comment.component.ts
import { Component, OnInit, Input } from '@angular/core';
import { CommentItem } from '../model/postDetails';
import { DevRantApiService } from '../Service/devrant_api';
import { LoaderService } from '../loader/loader.service';
import { Router } from '@angular/router';
import { PostDetailsRefreshService } from '../rant-details/rant-details.service';

@Component({
  selector: 'app-comment',
  templateUrl: './comment.component.html',
  styleUrls: ['./comment.component.css']
})
export class CommentComponent implements OnInit {

  @Input() data;
  comment:CommentItem;
  ismyComment:boolean;
  id:any;
 
  
  constructor(private devrantApi:DevRantApiService,private loaderService:LoaderService,private router: Router, private refreshService: PostDetailsRefreshService,) {

// console.log("comment",this.comment);
var url = window.location.pathname;
    var urlsplit = url.split("/").slice(-1)[0];
    console.log("id :",urlsplit);
    this.id=urlsplit;
   }

  ngOnInit() {
    this.comment=this.data;
    this.ismyComment=this.comment.isMyComment;
    console.log("comment",this.comment);
  }

  deleteComment(){
    this.loaderService.display(true);
    this.devrantApi.deleteComment(this.id,this.comment.id).subscribe(data => {
      console.log("post list call");
      // this.data=data;
      if(data.ok){

        console.log(data);
        // this.post=data.post;
        // this.voteService.update(this.post);
        // this.isMyPost=data.post.isMyPost;
        this.loaderService.display(false);
        this.refreshService.refresh(true);
        
// this.router.navigateByUrl('/rant/'+this.id);
        
      }else{
      
      }
    });
  }

}

<section class="comment">
    <div class="comment__inner">
      <div class="comment__body">
        <div class="profile">
          <div class="profile__picture">
            <svg height="36" width="36">
              <circle cx="18" cy="18" r="18" fill="#5c5f6f" />
            </svg>
          </div>
          <div class="profile__name">
            {{comment.author}}
          </div>
        </div>
        <div class="post__details">
            {{comment.comment}}
          <br />
        </div>
      </div>
    </div>
    <div class="comment__footer">
      <div class="comment__delete" *ngIf="ismyComment" (click)="deleteComment()">DELETE</div>
      <div class="comment__time"> {{comment.displayTime}}</div>
    </div>
  </section>
